### ISSUE TITLE
Suggestions support dynamic page layouts

### ISSUE THREAD

**Issue by Strypper** [tuyen-vuduc/chick-and-paddy-dotnet-maui#4]
Since devices like iPad and Galaxy Fold are been in the market for a while they continue to be users top picked devices. It's would be a good practice if we can support those devices too 

**Approach**
In one page we will have multiple states or visual states appear visible based on the windows width of the application. And since they are live in the same page with the same services injections, all the states can be remained and reused across state

**Comment by tuyen-vuduc** [comment]
This is a good catch; however, it is very specific for a device type. In this template, I don't want to overcomplex. If there is a demo to support page resize by Window size, it'll be in a different repo.
